# Generated by Django 4.2.9 on 2026-02-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_pendingcryptopayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingcryptopayment',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
