# Generated by Django 4.2.9 on 2026-02-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_pendingcryptopayment_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('wallet_topup', 'Wallet Top-up'), ('booking_payment', 'Booking Payment'), ('refund', 'Refund'), ('host_payout', 'Host Payout'), ('withdrawal', 'Withdrawal')], default='wallet_topup', max_length=30),
        ),
    ]
