# Generated by Django 4.2.9 on 2026-02-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('booking', 'Booking'), ('cancellation', 'Cancellation'), ('review', 'Review'), ('system', 'System'), ('payout', 'Payout')], default='system', max_length=20),
        ),
    ]
